// Which clipboard contents must NOT land in the history.
//
// 1. Hard signals set by the copying app (same rules as Windows' own clipboard history, Win+V):
//    - format "ExcludeClipboardContentFromMonitorProcessing" present           -> skip
//    - format "CanIncludeInClipboardHistory" with DWORD 0                       -> skip
//    - format "Clipboard Viewer Ignore" present (KeePass & co.)                 -> skip
//    - macOS equivalents (org.nspasteboard.ConcealedType/TransientType/AutoGeneratedType) for portability
// 2. The clipboard owner is a known password manager process                   -> skip
// 3. Content heuristics (conservative, each one explainable):
//    - PEM private key blocks, well-known API-token prefixes, JWTs
//    - credit card numbers (Luhn-valid, 13–19 digits)
//    - "password-like": one token, 8–64 chars, >= 3 character classes, high entropy
//      (can be switched off in settings: `skipPasswordLike`)

export interface ClipboardFlags {
  /** ExcludeClipboardContentFromMonitorProcessing is on the clipboard */
  excludeFromMonitor?: boolean;
  /** value of CanIncludeInClipboardHistory (undefined = format absent) */
  canIncludeInHistory?: number;
  /** "Clipboard Viewer Ignore" is on the clipboard */
  viewerIgnore?: boolean;
  /** macOS pasteboard markers (org.nspasteboard.*) */
  concealed?: boolean;
  transient?: boolean;
  /** executable name of the clipboard owner (e.g. "KeePassXC.exe") */
  ownerProcess?: string | null;
}

export type SkipReason =
  | 'exclude-format'
  | 'history-disallowed'
  | 'viewer-ignore'
  | 'concealed'
  | 'password-manager'
  | 'private-key'
  | 'api-token'
  | 'credit-card'
  | 'password-like'
  | 'ignored-app';

export interface SensitiveOptions {
  skipPasswordLike: boolean;
  /** extra executable names (lower case, with or without .exe) whose copies are ignored */
  ignoredApps: string[];
}

export const DEFAULT_SENSITIVE: SensitiveOptions = { skipPasswordLike: true, ignoredApps: [] };

const PASSWORD_MANAGERS = [
  '1password', 'keepass', 'keepassxc', 'bitwarden', 'dashlane', 'lastpass', 'keeper', 'keeperpasswordmanager',
  'enpass', 'nordpass', 'roboform', 'protonpass', 'proton pass', 'passwordsafe', 'pwsafe', 'sticky password',
  'stickypassword', 'zoho vault', 'myki', 'passbolt', 'buttercup', 'kee', 'authy', 'authy desktop',
];

function exeBase(name: string): string {
  const b = name.replace(/\\/g, '/').split('/').pop() ?? name;
  return b.toLowerCase().replace(/\.exe$/, '').trim();
}

export function isPasswordManager(owner: string | null | undefined, extra: string[] = []): boolean {
  if (!owner) return false;
  const b = exeBase(owner);
  if (PASSWORD_MANAGERS.includes(b)) return true;
  return extra.map(exeBase).includes(b);
}

export function flagsReason(f: ClipboardFlags, opts: SensitiveOptions = DEFAULT_SENSITIVE): SkipReason | null {
  if (f.excludeFromMonitor) return 'exclude-format';
  if (f.canIncludeInHistory !== undefined && f.canIncludeInHistory === 0) return 'history-disallowed';
  if (f.viewerIgnore) return 'viewer-ignore';
  if (f.concealed || f.transient) return 'concealed';
  if (f.ownerProcess && PASSWORD_MANAGERS.includes(exeBase(f.ownerProcess))) return 'password-manager';
  if (f.ownerProcess && opts.ignoredApps.map(exeBase).includes(exeBase(f.ownerProcess))) return 'ignored-app';
  return null;
}

const TOKEN_PATTERNS: RegExp[] = [
  /^sk-(?:proj-|ant-)?[A-Za-z0-9_-]{20,}$/,        // OpenAI / Anthropic style
  /^gh[pousr]_[A-Za-z0-9]{30,}$/,                 // GitHub
  /^github_pat_[A-Za-z0-9_]{40,}$/,
  /^xox[abposr]-[A-Za-z0-9-]{10,}$/,              // Slack
  /^AKIA[0-9A-Z]{16}$/,                            // AWS access key id
  /^AIza[0-9A-Za-z_-]{35}$/,                       // Google API key
  /^glpat-[A-Za-z0-9_-]{20,}$/,                    // GitLab
  /^(?:sk|rk)_live_[A-Za-z0-9]{20,}$/,             // Stripe secret
  /^cvpair1\.[A-Za-z0-9_-]{40,}$/,                 // ClipVault pairing code (contains the vault key)
  /^eyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{16,}$/, // JWT
];

export function luhnValid(digits: string): boolean {
  let sum = 0;
  let alt = false;
  for (let i = digits.length - 1; i >= 0; i--) {
    let n = digits.charCodeAt(i) - 48;
    if (n < 0 || n > 9) return false;
    if (alt) {
      n *= 2;
      if (n > 9) n -= 9;
    }
    sum += n;
    alt = !alt;
  }
  return sum % 10 === 0;
}

export function shannonBitsPerChar(s: string): number {
  const counts = new Map<string, number>();
  for (const ch of s) counts.set(ch, (counts.get(ch) ?? 0) + 1);
  const n = [...s].length;
  let h = 0;
  for (const c of counts.values()) {
    const p = c / n;
    h -= p * Math.log2(p);
  }
  return h;
}

export function looksLikePassword(t: string): boolean {
  if (t.length < 8 || t.length > 64 || /\s/.test(t)) return false;
  if (/^https?:\/\//i.test(t) || /^[\w.+-]+@[\w-]+\.[\w.]+$/.test(t)) return false; // url / email
  if (/^[A-Za-z]:\\|^\\\\|^\/|^~\//.test(t)) return false;                         // paths
  if (/^[0-9a-f-]+$/i.test(t)) return false;                                         // hex, uuids, hashes
  if (/^[A-Za-z]+$/.test(t) || /^\d+$/.test(t)) return false;
  if (/^[\w-]+\.[a-z]{2,6}$/i.test(t)) return false;                                  // file.ext, domain.tld
  if (/^[a-z]+(?:[A-Z][a-z]+)+\d*$/.test(t) || /^[a-z]+(?:_[a-z0-9]+)+$/.test(t)) return false; // camelCase / snake_case
  if (/^[A-Za-z][a-z]+\d{1,6}$/.test(t)) return false;                                  // word + number ("Rechnung2026")
  let classes = 0;
  if (/[a-z]/.test(t)) classes++;
  if (/[A-Z]/.test(t)) classes++;
  if (/\d/.test(t)) classes++;
  if (/[^A-Za-z0-9]/.test(t)) classes++;
  if (classes < 3) return false;
  return shannonBitsPerChar(t) >= 3.0;
}

export function textReason(raw: string, opts: SensitiveOptions = DEFAULT_SENSITIVE): SkipReason | null {
  const t = raw.trim();
  if (!t) return null;
  if (/-----BEGIN (?:[A-Z]+ )?PRIVATE KEY-----/.test(t) || /-----BEGIN OPENSSH PRIVATE KEY-----/.test(t)) return 'private-key';
  if (t.length <= 400 && !/\s/.test(t) && TOKEN_PATTERNS.some((rx) => rx.test(t))) return 'api-token';
  const compact = t.replace(/[\s-]/g, '');
  if (/^\d{13,19}$/.test(compact) && t.length <= 23 && luhnValid(compact)) return 'credit-card';
  if (opts.skipPasswordLike && looksLikePassword(t)) return 'password-like';
  return null;
}
