// The only place that touches the REAL clipboard (Electron main process). Never imported by tests.
// Electron >= 44: the clipboard API is async and W3C-shaped (read() -> ClipboardItem[], readText(), write()).
// Raw OS formats: `electron application/osclipboard;format="<name>"`.
import { clipboard, ClipboardItem, nativeImage, type NativeImage } from 'electron';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { makePrint, fineRaster, FINE_LONG_EDGE, type Bitmap } from '../core/dedupe';
import type { ClipboardAdapter } from '../core/watcher';
import type { ClipboardFlags } from '../core/sensitive';
import type { NewImage, FineLoader } from '../core/store';
import type { Platform, WindowRef } from '../platform/types';

const THUMB_EDGE = 192;
const raw = (format: string) => `electron application/osclipboard;format="${format}"`;

function bitmapOf(img: NativeImage, longEdge: number): Bitmap {
  const { width: w, height: h } = img.getSize();
  const s = Math.min(1, longEdge / Math.max(w, h));
  const small = s < 1 ? img.resize({ width: Math.max(1, Math.round(w * s)), height: Math.max(1, Math.round(h * s)), quality: 'good' }) : img;
  const sz = small.getSize();
  return { width: sz.width, height: sz.height, data: new Uint8Array(small.toBitmap()), order: 'bgra' };
}

export function imageFromNative(img: NativeImage, pngBytes?: Buffer): NewImage | null {
  if (img.isEmpty()) return null;
  const { width: w, height: h } = img.getSize();
  if (!w || !h) return null;
  const png = pngBytes ?? img.toPNG();
  const s = Math.min(1, THUMB_EDGE / Math.max(w, h));
  const thumbPng = s < 1 ? img.resize({ width: Math.max(1, Math.round(w * s)), height: Math.max(1, Math.round(h * s)), quality: 'good' }).toPNG() : null;
  const bm = bitmapOf(img, FINE_LONG_EDGE);
  return { png, thumbPng, w, h, print: makePrint(bm, w, h), fine: fineRaster(bm, w, h) };
}

const fineCache = new Map<string, Uint8Array>();
export const loadFineFromDisk: FineLoader = (item, abs) => {
  const hit = fineCache.get(item.id);
  if (hit) return hit;
  const img = nativeImage.createFromPath(abs);
  if (img.isEmpty()) return null;
  const f = fineRaster(bitmapOf(img, FINE_LONG_EDGE), item.w ?? img.getSize().width, item.h ?? img.getSize().height);
  if (fineCache.size > 64) fineCache.clear();
  fineCache.set(item.id, f);
  return f;
};

async function blobBuffer(b: unknown): Promise<Buffer | null> {
  if (b && typeof (b as Blob).arrayBuffer === 'function') return Buffer.from(await (b as Blob).arrayBuffer());
  if (typeof b === 'string') return Buffer.from(b, 'utf8');
  return null;
}

export class ElectronClipboardAdapter implements ClipboardAdapter {
  private items: ClipboardItem[] | null = null;
  private itemsAt = 0;
  constructor(private platform: Platform) {}

  /** clipboard.read() at most once per capture (cached for 100 ms) */
  private async read(): Promise<ClipboardItem[]> {
    const now = Date.now();
    if (this.items && now - this.itemsAt < 100) return this.items;
    try { this.items = await clipboard.read(); } catch { this.items = []; }
    this.itemsAt = now;
    return this.items;
  }
  private async types(): Promise<string[]> {
    return (await this.read()).flatMap((i) => i.types);
  }

  sequence(): number | null {
    return this.platform.clipboardSequence();
  }

  async fingerprint(): Promise<string> {
    // only used without a sequence number (not on Windows): types + text + image bytes hash
    this.items = null;
    const items = await this.read();
    const h = createHash('sha1');
    for (const it of items) {
      h.update(it.types.join(','));
      for (const t of it.types) {
        if (t === 'text/plain' || t.startsWith('image/')) {
          try { const b = await blobBuffer(await it.getType(t)); if (b) h.update(b); } catch { /* type vanished */ }
        }
      }
    }
    return h.digest('hex');
  }

  async flags(): Promise<ClipboardFlags> {
    const f = this.platform.clipboardFlags();
    if (process.platform === 'darwin') {
      const has = async (fmt: string) => { try { return await clipboard.has(raw(fmt)); } catch { return false; } };
      if (await has('org.nspasteboard.ConcealedType')) f.concealed = true;
      if ((await has('org.nspasteboard.TransientType')) || (await has('org.nspasteboard.AutoGeneratedType'))) f.transient = true;
    }
    return f;
  }

  async readFiles(): Promise<string[]> {
    const native = this.platform.readFileList();
    if (native) return native;
    if (process.platform !== 'darwin') return [];
    try {
      for (const it of await this.read()) {
        const t = it.types.find((x) => /public\.file-url|text\/uri-list/.test(x));
        if (!t) continue;
        const b = await blobBuffer(await it.getType(t));
        const s = b?.toString('utf8').split(/\r?\n/).find((l) => l.startsWith('file://'));
        if (s) return [fileURLToPath(s.trim())];
      }
    } catch { /* no files */ }
    return [];
  }

  async readText(): Promise<string> {
    try { return await clipboard.readText(); } catch { return ''; }
  }

  async hasImage(): Promise<boolean> {
    this.items = null; // fresh read for the capture
    return (await this.types()).some((t) => t.startsWith('image/'));
  }

  async readImage(): Promise<NewImage | null> {
    for (const it of await this.read()) {
      const t = it.types.find((x) => x === 'image/png') ?? it.types.find((x) => x.startsWith('image/'));
      if (!t) continue;
      const b = await blobBuffer(await it.getType(t));
      if (!b?.length) continue;
      const img = nativeImage.createFromBuffer(b);
      return imageFromNative(img, t === 'image/png' ? b : undefined);
    }
    return null;
  }
}

// ---------------------------------------------------------------- writing back (copy)
export async function writeTextToClipboard(text: string): Promise<void> {
  await clipboard.writeText(text);
}
export async function writeImageToClipboard(abs: string): Promise<void> {
  const img = nativeImage.createFromPath(abs);
  if (img.isEmpty()) return;
  await clipboard.write([new ClipboardItem({ 'image/png': new Blob([new Uint8Array(img.toPNG())], { type: 'image/png' }) })]);
}
export async function writeFilesToClipboard(platform: Platform, paths: string[], owner: WindowRef | null): Promise<boolean> {
  if (platform.writeFileList(paths, owner)) return true;
  await clipboard.writeText(paths.join(process.platform === 'win32' ? '\r\n' : '\n'));
  return false;
}
